name: pod_player
description: Flutter video player for web & mobile devices, and also supports playing video from youtube and vimeo.
version: 0.0.1
homepage: https://github.com/newtaDev/pod_player

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # ui
  lottie:
  # services
  video_player: ^2.3.0
  http:
  get:
  wakelock: 
  universal_html:
  youtube_explode_dart: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  assets:
    - assets/
