name: fl_video_player
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ui
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  # 
  video_player: ^2.2.4
  http: ^0.13.3
  get: ^4.3.8
  lottie: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - ./assets/lottie/